### ISSUE TITLE
MathJax new macros

### ISSUE THREAD

**Issue by stla** [ramnathv/poirot#26]
My blogification does not work and I'm suspecting this is due to new MathJax macros.
Using `knitr`, one can define a new macro by writing

```
\(\newcommand{\indic}{{\bf 1}}\)
```

at the beginning of the file, or 

```
<script type='text/x-mathjax-config'>
  MathJax.Hub.Config({
  TeX: {
    Macros: {
      indic: "{\\bf 1}"
    }
  }
  });
</script>
```

But when blogifying I get this error at the end of the blogification:

```
Error in parseTemplate(template, partials = as.environment(partials),  : 
  Template does not close the following tags: \Bigl([\indic_I]\otimes[\indic_J]\Bigr)}^\perp
```

I have also tried to include 

```
<script type='text/x-mathjax-config'>
  MathJax.Hub.Config({
  TeX: {
    Macros: {
      indic: "{\\bf 1}"
    }
  }
  });
</script>
```

at the beginning of `index.Rmd` file. The script appears in `index.html` but there's still the error message.

**Comment by ramnathv** [comment]
The error occurs because `slidify` is interpreting `{{\bf 1}}` as closing a mustache template by name `bf 1`. One way to solve it is to put this macro inside a slide marked with `.RAW`. Any content within a slide marked with `.RAW` passes through without any template expansion.

This option is not documented and can be expected to change as I figure out a cleaner way to achieve this, but for now this will do.

```
--- .RAW
\(\newcommand{\indic}{{\bf 1}}\)

---
```

**Comment by stla** [comment]
I have not been able to successfully apply your proposal, perhaps I have not understand where to write that. Inside the body of the `Rmd` file, the same error occurs.

**Comment by ramnathv** [comment]
Do you have a link to the place where you tried this?

**Comment by stla** [comment]
For example I tried

```
--- 
title: The balanced ANOVA model with random effects 
date : 2014-04-06
--- &lead

**(article still under construction)**

--- .RAW
\(\newcommand{\indic}{{\bf 1}}\)

---
```

at the beginning of [this file](https://github.com/stla/stlapblog/blob/gh-pages/posts/Anova1random.Rmd).

Actually the same error occurs if I don't try to define `\indic` anywhere, thus it should not be related to the braces.

**Comment by ramnathv** [comment]
I checked your HTML file and for some reason the `---` is not being interpreted as a slide separator and being converted to HTML. Can you check if you have an empty space on the line before the `--- .RAW` since slidify expects a pattern of the kind `\n\n---` to identify slide separators and so any empty characters in the preceding line trip it up.

This should fix your error, but markdown will still wrap this command up in `<p></p>` tags and the question is if that would affect the macro. Slidify still uses the `markdown` package and NOT the `rmarkdown` package which uses `pandoc` and hence has a latex passthrough mode. 

Let us first try to debug it this way and then figure out other options.

**Comment by ramnathv** [comment]
Looking at this [file](https://github.com/stla/stlapblog/blob/3a5fceb4dec6dcf245bcfb722b02ad7f0da538b3/posts/Anova1random.html), it seems like your Rmd is being knitted by `knit2html` and not `slidify`, which is why everything is being converted into HTML.

**Comment by stla** [comment]
I'm afraid the error is due to another reason: 

```
\underset{\text{'total'}}{\underbrace{{\Bigl([\indic_I]\otimes[\indic_J]\Bigr)}^\perp}}
```

The MathJax code between the pair of doubles braces is exactly what we see in the error message:

```
Error in parseTemplate(template, partials = as.environment(partials),  : 
  Template does not close the following tags: \Bigl([\indic_I]\otimes[\indic_J]\Bigr)}^\perp
```

**Comment by ramnathv** [comment]
So anywhere you see double braces, slidify will try to expand it as a template. The only way to solve it currently is to wrap such statements between `--- .RAW` and `---` tags, so that slidify does not attempt to expand them. Let me see if I can come up with a cleaner mechanism to achieve this.

Let me know if the wrapping approach solves the problem in first place.

**Comment by stla** [comment]
I have not been able to make anything work with `.RAW`. I have finally found two tricks solving my problems, to avoid the opening double braces :

```
\(\newcommand{\indic}{\mathbf{1}}\)
```

and 

```
\underset{\text{'total'}}{\underbrace{ {\Bigl([\indic_I]\otimes[\indic_J]\Bigr)}^\perp}}
```

(a space between the braces). 

The script in `index.html`

```
<script type='text/x-mathjax-config'>
  MathJax.Hub.Config({
  TeX: {
    Macros: {
      indic: "{\\bf 1}"
    }
  }
  });
</script>
```

does not seem to have an effect.

**Comment by ramnathv** [comment]
I am surprised that `.RAW` did not work. Can you point me to your Rmd source so that I can investigate. Concerning the solution you came up with, does it solve everything for you, or something still does not work. It was not clear to me.

**Comment by stla** [comment]
Yes, everything works fine now. 

The `Rmd` file is https://github.com/stla/stlapblog/blob/gh-pages/posts/Anova1random.Rmd (its [rendering here](http://stla.github.io/stlapblog/posts/Anova1random.html))

Thanks for your help !

**Comment by ramnathv** [comment]
Great. I will figure out a cleaner way to handle latex, so that this is easier. It is good that you were able to arrive at a workaround.
